### PR TITLE
Set versions of all Symfony packages

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #57

### CODE REVIEW

**Comment by szepeviktor** [comment]
Windows alert!!
I should rewrite this to a single line of `jq`.

**Comment by szepeviktor** [comment]
@PabloKowalczyk Now it is tiny and working.

**Comment by PabloKowalczyk** [comment]
Thank You @szepeviktor.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
