### PR TITLE
Event Unique Key implementation

### PR DESCRIPTION
**Pull request by lucatacconi**
In the PR there is a possible solution to calculate a constant unique identifier for events.

This solution is linked to issue #33 and could be the first piece towards creating a launcher that allows you to launch a task based on the unique identifier.

@PabloKowalczyk, I haven't build the tests for the methods yet but I would like to know what you thought first.

### CODE REVIEW

**Comment by lucatacconi** [comment]
I added EventUniqueKey display in task list shown by vendor/bin/crunz schedule:list command

**Comment by lucatacconi** [comment]
For now all green lights in the tests. It must be considered that there is still a lack of tests on the new methods implemented

**Comment by lucatacconi** [comment]
@PabloKowalczyk Have you had a chance to see the work I've done? If you want to contact me directly there are my contacts on the github profile

**Comment by PabloKowalczyk** [comment]
Hello, for some reason there is no CI checks. Maybe creating new PR will solve this issue?

**Pull request closed without merging**
